name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: mfcDuDownloadCodeGenerator.sln

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        build_config:
          - vs2019_ci_dynamic
          - vs2022_ci_static

        include:
          - build_config: vs2019_ci_dynamic
            os: windows-2019
            vs_version: vs2019
            upx: 'false'
          - build_config: vs2022_ci_static
            os: windows-2022
            vs_version: vs2022
            upx: 'true'

    runs-on: "${{ matrix.os }}"

    steps:
    - name: ğŸ›ï¸ checkout
      uses: actions/checkout@v3

    - name: ğŸ­ prepare MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: ğŸ­ prepare msys2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          git
          upx
          zip

    - name: ğŸ”§ build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: |
        msbuild /m `
          /p:Configuration=${{ matrix.build_config }} `
          ${{env.SOLUTION_FILE_PATH}}

    - name: ğŸ—œï¸ upx?
      shell: msys2 {0}
      run: |
        if [ "${{ matrix.upx }}" == "true" ]; then
          upx -9 x64/${{ matrix.build_config }}/*.exe
        fi

    - name: ğŸ—œï¸ archive binaries
      uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: x64/${{ matrix.build_config }}

    - name: ğŸ“¦ package for release
      shell: msys2 {0}
      run: |
        cd "x64/${{ matrix.build_config }}"
        zip -9 "../../ducode.${{ matrix.vs_version }}.$(git describe --abbrev=0).zip" *.exe

    - name: ğŸ“ draft release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        body: "<to be filled>"
        draft: true
        # note you'll typically need to create a personal access token
        # with permissions to create releases in the other repo
        token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        files: |
          *.zip
